# Generated by Django 2.1.5 on 2019-01-31 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Targowisko'), (2, 'Ryneczek'), (3, 'Giełda tematyczna'), (4, 'Jarmark okoliczościowy'), (5, 'Targi branżowe'), (6, 'Rzemieślnik'), (7, 'Centrum Handlowe'), (8, 'Giełda rolno-towarowa')], verbose_name='Rodzaj')),
                ('administrator', models.CharField(max_length=255, verbose_name='Zarządca')),
                ('address', models.CharField(max_length=128, verbose_name='Adres')),
                ('geolocation', models.CharField(max_length=100, verbose_name='Współrzędne geograficzne')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy jest czynne')),
                ('cured_area', models.IntegerField(choices=[(1, 'Tak'), (2, 'Częściowo'), (3, 'Nie'), (4, 'Brak informacji')], verbose_name='Utwardzona nawierzchnia')),
                ('is_indoor', models.IntegerField(choices=[(1, 'Tak'), (2, 'Częściowo'), (3, 'Nie'), (4, 'Brak informacji')], verbose_name='Zadaszenie przejść')),
                ('handicaps', models.IntegerField(choices=[(1, 'Tak'), (2, 'Częściowo'), (3, 'Nie'), (4, 'Brak informacji')], verbose_name='Udogodnienia dla niepełnosprawnych')),
                ('is_toilet', models.BooleanField(verbose_name='Toalety')),
                ('public_transport', models.BooleanField(verbose_name='Zasięg transportu publicznego')),
                ('taxi_range', models.BooleanField(verbose_name='Zasięg taxi')),
                ('parking', models.IntegerField(choices=[(1, 'Brak'), (2, 'Płatny strzeżony'), (3, 'Płatny niestrzeżony'), (4, 'Bezpłatny')], default=1, verbose_name='Parking')),
                ('cycle_places', models.BooleanField(verbose_name='Miejsca dla rowerów')),
                ('radio_info', models.BooleanField(verbose_name='Radiowęzeł')),
                ('atm_nearby', models.BooleanField(verbose_name='Bankomat w pobliżu')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Opis')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Zdjęcia')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='add_photos/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_id', to='targi.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='TownAndCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('province', models.CharField(choices=[('DS', 'dolnośląskie'), ('LB', 'lubelskie'), ('LD', 'łódzkie'), ('MZ', 'mazowieckie'), ('PK', 'podkarpackie'), ('PM', 'pomorskie'), ('SK', 'świętokrzyskie'), ('WP', 'wielkopolskie'), ('KP', 'kujawsko-pomorskie'), ('LS', 'lubuskie'), ('MP', 'małopolskie'), ('OP', 'opolskie'), ('PL', 'podlaskie'), ('SL', 'śląskie'), ('WM', 'warmińsko-mazurskie'), ('zp', 'zachodniopomorskie')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='products',
            field=models.ManyToManyField(to='targi.Products', verbose_name='Przedmiot handlu'),
        ),
        migrations.AddField(
            model_name='market',
            name='town_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='town_address', to='targi.TownAndCities', verbose_name='Miejscowość'),
        ),
    ]
