# Generated by Django 2.1.5 on 2019-02-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='photo_1',
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_id', to='targi.Market', verbose_name='Targ'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='add_photos/', verbose_name='Zdjęcia'),
        ),
    ]
