# Generated by Django 2.1.5 on 2019-02-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targi', '0003_market_photo_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='forms/', verbose_name='Plik .doc .docx')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
