# Generated by Django 2.1.5 on 2019-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targi', '0005_auto_20190205_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='geolocation',
            field=models.CharField(max_length=64, verbose_name='Współrzędne geograficzne'),
        ),
        migrations.AlterField(
            model_name='market',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='forms/', verbose_name='Plik .docx'),
        ),
    ]
